// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConvertToYAML(arg1:string,arg2:boolean):Promise<main.JSONResponse>;

export function FormatJSON(arg1:string,arg2:string,arg3:boolean):Promise<main.JSONResponse>;

export function GetPathByOffset(arg1:string,arg2:number):Promise<string>;

export function GetPathOffset(arg1:string,arg2:string):Promise<main.PathInfo>;

export function MinifyJSON(arg1:string,arg2:boolean):Promise<main.JSONResponse>;

export function ProcessJSON(arg1:string,arg2:string,arg3:boolean):Promise<main.JSONResponse>;
