// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertToCSharpClass(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ConvertToCSharpClass'](arg1, arg2, arg3, arg4);
}

export function ConvertToGoStruct(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ConvertToGoStruct'](arg1, arg2, arg3, arg4);
}

export function ConvertToJavaClass(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ConvertToJavaClass'](arg1, arg2, arg3, arg4);
}

export function ConvertToPythonClass(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ConvertToPythonClass'](arg1, arg2, arg3, arg4);
}

export function ConvertToSQL(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ConvertToSQL'](arg1, arg2, arg3, arg4, arg5);
}

export function ConvertToTypeScriptInterface(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ConvertToTypeScriptInterface'](arg1, arg2, arg3, arg4);
}

export function ConvertToYAML(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConvertToYAML'](arg1, arg2, arg3);
}

export function FormatJSON(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FormatJSON'](arg1, arg2, arg3, arg4);
}

export function GetPathByOffset(arg1, arg2) {
  return window['go']['main']['App']['GetPathByOffset'](arg1, arg2);
}

export function GetPathOffset(arg1, arg2) {
  return window['go']['main']['App']['GetPathOffset'](arg1, arg2);
}

export function MinifyJSON(arg1, arg2, arg3) {
  return window['go']['main']['App']['MinifyJSON'](arg1, arg2, arg3);
}

export function ProcessJSON(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ProcessJSON'](arg1, arg2, arg3, arg4);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function WriteFileDirect(arg1, arg2) {
  return window['go']['main']['App']['WriteFileDirect'](arg1, arg2);
}
