// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertToYAML(arg1, arg2) {
  return window['go']['main']['App']['ConvertToYAML'](arg1, arg2);
}

export function FormatJSON(arg1, arg2, arg3) {
  return window['go']['main']['App']['FormatJSON'](arg1, arg2, arg3);
}

export function GetPathByOffset(arg1, arg2) {
  return window['go']['main']['App']['GetPathByOffset'](arg1, arg2);
}

export function GetPathOffset(arg1, arg2) {
  return window['go']['main']['App']['GetPathOffset'](arg1, arg2);
}

export function MinifyJSON(arg1, arg2) {
  return window['go']['main']['App']['MinifyJSON'](arg1, arg2);
}

export function ProcessJSON(arg1, arg2, arg3) {
  return window['go']['main']['App']['ProcessJSON'](arg1, arg2, arg3);
}
