// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConvertToCSharpClass(arg1:string,arg2:boolean,arg3:boolean,arg4:string):Promise<main.JSONResponse>;

export function ConvertToGoStruct(arg1:string,arg2:boolean,arg3:boolean,arg4:string):Promise<main.JSONResponse>;

export function ConvertToJavaClass(arg1:string,arg2:boolean,arg3:boolean,arg4:string):Promise<main.JSONResponse>;

export function ConvertToPythonClass(arg1:string,arg2:boolean,arg3:boolean,arg4:string):Promise<main.JSONResponse>;

export function ConvertToSQL(arg1:string,arg2:boolean,arg3:boolean,arg4:string,arg5:string):Promise<main.JSONResponse>;

export function ConvertToTypeScriptInterface(arg1:string,arg2:boolean,arg3:boolean,arg4:string):Promise<main.JSONResponse>;

export function ConvertToYAML(arg1:string,arg2:boolean,arg3:boolean):Promise<main.JSONResponse>;

export function FormatJSON(arg1:string,arg2:string,arg3:boolean,arg4:boolean):Promise<main.JSONResponse>;

export function GetPathByOffset(arg1:string,arg2:number):Promise<string>;

export function GetPathOffset(arg1:string,arg2:string):Promise<main.PathInfo>;

export function MinifyJSON(arg1:string,arg2:boolean,arg3:boolean):Promise<main.JSONResponse>;

export function ProcessJSON(arg1:string,arg2:string,arg3:boolean,arg4:boolean):Promise<main.JSONResponse>;

export function ReadFile(arg1:string):Promise<main.JSONResponse>;

export function RegisterAsDefaultEditor():Promise<main.JSONResponse>;

export function SaveFile(arg1:string,arg2:string):Promise<main.JSONResponse>;

export function WriteFileDirect(arg1:string,arg2:string):Promise<main.JSONResponse>;
